c-------------------------------------------------------
c       Masses for all the particles in fm^(-1)
c-------------------------------------------------------
      real*8  mel,mmu,mn,ms,mr,mw,mlam, msig, mcas, mk, fpi2
      parameter (mel=2.58957e-3, mmu=0.5357, mn=4.7535)  
      parameter (ms=3.0406,  mw=3.9659, mr=3.8970)  

      REAL*8 GS,GW,GR,B,C
      parameter (GS=9.5800, GW=8.7069, GR=8.5295)
      parameter (B=0.008660, C= -0.002421)

